name: PHP Copy Past Detector

on:
  push:
    branches: [ "*" ]
  # pull_request:
  #   branches: [ "*" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer install

    - name: PHP Copy Paste Detector
      # You may pin to the exact commit or the version.
      # uses: StephaneBour/actions-php-cpd@4b842d8ecc9f9a6a1abce48b78590e50eed3715b
      uses: StephaneBour/actions-php-cpd@8.1
      with:
        args: './src/'
