name: phpmd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
    bulild:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
            uses: actions/checkout@v2

            - name: Setup PHP environment
            uses: shivammathur/setup-php@v2

        with:
          coverage: none
          tools: phpmd

        - name: Run PHPMD
        run: phpmd . github phpmd.ruleset.xml --exclude 'tests/*,vendor/*'
